//
//  BTFortuneCard.h
//  BetterIt
//
//  Created by Jayden on 04/05/2016.
//  Copyright (c) 2016 BetterIt. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface BTFortuneCard : NSObject

// Drawing Methods
+ (void)drawFortune_cardCanvasWithFortuneText: (NSString*)fortuneText;

@end
